### ISSUE TITLE
Installation Clarity

### ISSUE THREAD

**Issue by dsanghan** [zorgiepoo/sparkle-ui-xpc-issues#38]
Thanks for all the work on this fork!

My app uses both sandboxing and code-signing.

I wanted some more clarity on which XPC services to include.

You mention: 

> If you want to code sign Sparkle's installer tools (Autoupdate and Updater.app), then you should include the InstallerLauncher XPC service regardless if you have a sandboxed application or not. Note Sparkle keeps a copy of these tools inside its framework's resources because using the XPC services is optional, and they need to be inside the XPC service for security reasons. If you wish, you can remove them from the framework if you use the InstallerLauncher service.
1. Does this mean I don't need to also copy over the InstallerLauncher into my project if I keep the XPC's inside the framework resources?
2. I don't see the XPC's inside the resources directory on doing a make-release. They are in the build products, just not linked into the framework->resources. Do I need to manually copy them into my project or into the framework or is it unnecessary?

**Comment by zorgiepoo** [comment]
If your application is sandboxed, you need to copy the XPC services into your app and add them to a "Copy Services" build phase (whose destination  is "XPC Services"). (The only XPC service you may not need is the Downloader one but that is only if your app has an exception for outgoing connections).

Since you need to include the InstallerLauncher service (because you're sandboxed), what this means is you don't need `Sparkle.framework/Resources/Autoupdate` and `Sparkle.framework/Resources/Updater.app` because they are also bundled in the service, so you can freely remove those if you wish.

XPC services are not included in the framework because they operate in an application namespace, not a framework one, and also because they are optional.

**Comment by dsanghan** [comment]
Makes sense. Thanks!
